In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
data=pd.read_csv("/Users/aadithyaram/Downloads/dataset.csv")

In [8]:
data.head()

Unnamed: 0                track_id                 artists  \
0           0  5SuOikwiRyPMVoIQDJUgSV             Gen Hoshino   
1           1  4qPNDBW1i3p13qLCt0Ki3A            Ben Woodward   
2           2  1iJBSr7s7jYXzM8EGcbK5b  Ingrid Michaelson;ZAYN   
3           3  6lfxq3CG4xtTiEg7opyCyx            Kina Grannis   
4           4  5vjLSffimiIP26QG5WcN2K        Chord Overstreet   

                                          album_name  \
0                                             Comedy   
1                                   Ghost (Acoustic)   
2                                     To Begin Again   
3  Crazy Rich Asians (Original Motion Picture Sou...   
4                                            Hold On   

                   track_name  popularity  duration_ms  explicit  \
0                      Comedy          73       230666     False   
1            Ghost - Acoustic          55       149610     False   
2              To Begin Again          57       210826     False   
3  Can't Help Falling In Love          71       201933     False   
4                     Hold On          82       198853     False   

   danceability  energy  ...  loudness  mode  speechiness  acousticness  \
0         0.676  0.4610  ...    -6.746     0       0.1430        0.0322   
1         0.420  0.1660  ...   -17.235     1       0.0763        0.9240   
2         0.438  0.3590  ...    -9.734     1       0.0557        0.2100   
3         0.266  0.0596  ...   -18.515     1       0.0363        0.9050   
4         0.618  0.4430  ...    -9.681     1       0.0526        0.4690   

   instrumentalness  liveness  valence    tempo  time_signature  track_genre  
0          0.000001    0.3580    0.715   87.917               4     acoustic  
1          0.000006    0.1010    0.267   77.489               4     acoustic  
2          0.000000    0.1170    0.120   76.332               4     acoustic  
3          0.000071    0.1320    0.143  181.740               3     acoustic  
4          0.000000    0.0829    0.167  119.949               4     acoustic  

[5 rows x 21 columns]

In [9]:
data1 = data.drop(['track_name'], axis=1)


In [10]:
data2=data1.drop(['track_genre'],axis=1)

In [11]:
data3=data2.drop(['artists'],axis=1)

In [12]:
import pandas as pd
from factor_analyzer import FactorAnalyzer

numeric_data = data3.select_dtypes(include=[int, float])

# Initialize the factor analyzer with the desired number of factors
n_factors = 3  
fa = FactorAnalyzer(n_factors)

fa.fit(numeric_data)

# Get factor loadings
factor_loadings = fa.loadings_

# Display the factor loadings
print("Factor Loadings:\n", factor_loadings)


Factor Loadings:
 [[-0.07693624 -0.0170646   0.12318684]
 [ 0.01837695  0.00150362  0.05878606]
 [ 0.12193363 -0.04583007 -0.26212337]
 [-0.22437609  1.02595979  0.37998063]
 [ 0.94932071 -0.01975735  0.03815333]
 [ 0.04056516  0.05425612 -0.01916564]
 [ 0.75055654  0.05795898  0.3251343 ]
 [-0.06855367 -0.09246323  0.10424691]
 [ 0.07195798  0.01492716  0.11772635]
 [-0.76347823 -0.09637543  0.13946317]
 [-0.17193059 -0.00426372 -0.64568374]
 [ 0.17691839 -0.2036185   0.09368267]
 [ 0.04402198  0.37005737  0.48564896]
 [ 0.29220018 -0.07312234 -0.00435362]
 [ 0.14041394  0.19025274  0.06585209]]
